<a href="https://colab.research.google.com/github/alicebu/My-Proyect/blob/main/Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structure**

DS are like variable, they *save* information. The difference is that DS can store more than 1 value.


Formaly, DS store a **sequence** of values which can be located with an index (sciling). Ex: list, vectors and matrices, databases.

Now, basic Python sucks!!! It lacks specialized tools. In this case, we need to install 'numpy'.



# 2 **1. Linear Algebra - Numpy**

Numpy (or Numerical Python) is collection of funtions and methods to handle DS.

This library works very well with other libraries and it is very popular.



In [5]:
# Install a library

import numpy as np



In [6]:
np.array

<function numpy.array>

# 2.2. Numpy arrays - vectors and matrices 

objets arranged by row and columns. With these object you can sum and multiply 

*Example 1*

let be x_{1} $x_{1}$

Let $a$ be a vector with 2 rows and 1 column

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUM VECTOR**. And the vector dimension or shape is $(2,1)$ or $(2 \times 1)$

*Example 2*

Let $b$ be a vectors with 1 rows and 2 column

\begin{equation}
a = \left[\begin{array}{c} b_{1} \\ b_{2}
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the vector dimension or shape is $(1,2)$ or $(1 \times 2)$


*Example 3*

A matrix has more than 1 row and more than 1 column.

Of course if the number of rows and columns are equal, it is called a *squared matrix*

In general , let $M$ be a matrix of dimension $(n,m)$ or $(n \times m)$

For the case of $n=3$ and $m=3$:

\begin{equation}
a = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1.3} \\
m_{2,1} & m_{2,2} & m_{2.3} \\
m_{3,1} & m_{3,2} & m_{3.3} \\
    \end{array}\right]
\end{equation}



In [7]:
# Example - column vector 

a = np.array([[4], [5], [6]])
print(a) 
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [8]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [9]:
# Example - Matrix 
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


# A nice track

In [10]:
# nr: store the number of rows
# nr: stores the number of columns
nr, nc = M.shape

# Size of DS

In python, size means the number of elements in a DS

In [11]:
M.size

9

In [12]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))

<class 'int'> <class 'numpy.ndarray'>


## 2.3 slicing

It is the same as string variable, only with minor modifications.

Let's see:

In [13]:
# Extract the 1st element

## column Vector
print(a[0,0])
print(type(a[0,0]))

## Row Vector
print(b[0,0])
print(type(a[0,0]))

## Matrix
print(M[1,1])

4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [14]:
# Extrac the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix 9


In [15]:
# Extract  subset

## Column Vector
print(a[0:2,0])

## Column Vector
print(a[0:2])

## Row Vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[4 5]
[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


In [16]:
## A custom sequence with a set step
a = 3
b = 25
s = 0.25
np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [17]:
## Linear space

a = 1
b = 5
n = 3

np.linspace(a, b, num = n)


a = 15
b = 17
n = 10

np.linspace(a, b, num = n)

array([15.        , 15.22222222, 15.44444444, 15.66666667, 15.88888889,
       16.11111111, 16.33333333, 16.55555556, 16.77777778, 17.        ])

### Random numbers

We are talking about probabilities, and of probabilistic distributions.

#### Uniform distribution over [0,1)

In [18]:
# A single vale
np.random.rand()

0.002021762957995943

In [19]:
# Example 1 - the coin toss
## Here we are going to simulate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [20]:
from numpy.random.mtrand import random
from numpy.random import rand
# Example 2- Ranking

## The idea is to print 'low' if the number is lower than 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is greater than 0.7

rnd = np.random.rand()

if np.random.rand() <= 0.3:
  print('Low', rnd)
elif np.random.rand() > 0.3 and rnd <= 0.7:
  print('Average', rnd)
else:
  print('High', rnd)


Low 0.9589388762962654


**Exercise**

Code the following game. Print the message
'You win!' if two coin tosses are heads and print 'You lose!' otherwise

In [21]:
if np.random.rand() <= 0.5:
  print('You win!')
else:
  print('You lose!')

You lose!


In [22]:
rnd = np.random.rand()

if np.random.rand() <= 0.5:
  print('You win!', rnd)
elif np.random.rand() > 0.5 and rnd <= 2.0:
  print('You lose!', rnd)
else:
  print('High', rnd)

You win! 0.6886852060435082


In [23]:
rnd = np.random.rand()

if np.random.rand() <= 0.5:
  print('Head', rnd)
elif np.random.rand() > 0.5 and rnd <= 2.0:
  print('Tails', rnd)
else:
  print('High', rnd)

High 0.2631499146650552


In [27]:
First_att = np.random.rand

if First_att <= 0.5:
  print('Head', First_att)
else:
  print('tails', First_att)




TypeError: ignored

In [ ]:
if First_att <= 0.5:
  print('Head', First_att)
else:
  print('tails', First_att)

Second_att = np.random.rand

if Second_att <= 0.5:
  print('Head', Second_att)
else:
  print('tails', Second_att)

if First_att <=0.5 and Second_att <=0.5:
  print('You win!')
else:
  print('You lose!')

In [30]:
#Solucion 2.0

First_attemept  = np.random.rand()
Second_attemept = np.random.rand()
results         = np.array([['Head', 'Tails']])
indx1           = int(round(First_attemept,0))
indx2           = int(round(Second_attemept,0))

if First_attemept <=0.5 and Second_attemept <=0.5:
  print('Head', First_attemept)
  print('Head', Second_attemept)
  print('You win!')
else:
  print(results[0,indx1], First_attemept)
  print(results[0,indx2], Second_attemept)
  print('You lose!')

Head 0.3237150551008281
Head 0.28346042618474543
You win!


In [29]:
# One dimensional array
np.random.rand(4)

array([0.77728734, 0.95152702, 0.00705754, 0.35073226])

#fourth try

In [37]:
tries = np.random.rand(2)


results         = np.array([['Head', 'Tails']])
indx1           = int(round(tries[0],0))
indx2           = int(round(tries[1],0))

if tries[0] <=0.5 and tries[1] <=0.5:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')
else:
  print(results[0,indx1], tries[0])
  print(results[0,indx2], tries[1])
  print('You lose!')

Tails 0.5769799639868366
Head 0.3362291908234536
You lose!


In [38]:
# two dimention

np.random.rand(7,8)

array([[0.6198169 , 0.14276875, 0.90391264, 0.94266186, 0.65298266,
        0.59735237, 0.22882445, 0.42098344],
       [0.95087327, 0.26236876, 0.12503238, 0.61621562, 0.96456471,
        0.04471757, 0.70225462, 0.94572835],
       [0.50290058, 0.49664801, 0.28469708, 0.43983851, 0.51611099,
        0.46674611, 0.28006041, 0.98111499],
       [0.78398447, 0.54427052, 0.1265448 , 0.55026284, 0.71836448,
        0.31098128, 0.37715524, 0.88814976],
       [0.72131036, 0.64940427, 0.27026758, 0.88979255, 0.9443631 ,
        0.79238826, 0.96409814, 0.43389641],
       [0.13290823, 0.9718005 , 0.93051325, 0.046369  , 0.67947342,
        0.33351397, 0.62920625, 0.14934813],
       [0.26846977, 0.06743179, 0.52887606, 0.14062352, 0.13483774,
        0.61196274, 0.85861631, 0.78178791]])

In [39]:
# One dimensional array
np.random.rand(2)

array([0.31666932, 0.88775353])

In [35]:
# One value
np.random.uniform(low = -1, high = 5) 

-0.29646686860088267

In [ ]:
# one dimensional

np.random.uniform.uniform(low= -10, high = 0, size = 10)

#Normal Distribution

In [44]:
# Stadard Normal - N ~ (0,1)

np.random.randn()
np.random.randn(8)
np.random.randn(7,5)


array([[ 0.73833037, -1.3957577 , -1.68379272, -1.65789181, -1.14510989],
       [ 0.01095953, -0.80619681,  0.99117631, -0.98463441, -1.15195436],
       [ 0.01868987,  0.35735897, -1.62601125, -0.43404084, -0.86753465],
       [-0.53816757,  0.59571064, -1.85713912, -1.91060939, -1.11158585],
       [ 0.04711351,  0.08034625,  0.13358034,  0.50279465,  0.22046517],
       [-0.49368836,  1.10893115, -1.04094163,  0.52382069, -0.77062754],
       [-0.73124396,  0.39742146, -0.65933413, -1.18739427,  0.40396971]])

In [46]:
from numpy.core.fromnumeric import size
# Normal - N ~ (mu, sigma)

mu     =0.001  #mean
sigma  =0.1    #std. desviation

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))


array([[-0.03630014],
       [-0.04402018],
       [ 0.21397787]])

# Random Inter

In [49]:
np.random.randint(low = 0, high = 10) # one value 
np.random.randint(low = 0, high = 10, size = 8) # one dimensional
np.random.randint(low = 0, high = 10, size = (2,3)) #two dimensional

array([[2, 9, 7],
       [6, 5, 7]])