<a href="https://colab.research.google.com/github/alicebu/My-Proyect/blob/main/Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structure**

DS are like variable, they *save* information. The difference is that DS can store more than 1 value.


Formaly, DS store a **sequence** of values which can be located with an index (sciling). Ex: list, vectors and matrices, databases.

Now, basic Python sucks!!! It lacks specialized tools. In this case, we need to install 'numpy'.



# 2 **1. Linear Algebra - Numpy**

Numpy (or Numerical Python) is collection of funtions and methods to handle DS.

This library works very well with other libraries and it is very popular.



In [11]:
# Install a library

import numpy as np



In [12]:
np.array

<function numpy.array>

# 2.2. Numpy arrays - vectors and matrices 

objets arranged by row and columns. With these object you can sum and multiply 

*Example 1*

let be x_{1} $x_{1}$

Let $a$ be a vector with 2 rows and 1 column

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUM VECTOR**. And the vector dimension or shape is $(2,1)$ or $(2 \times 1)$

*Example 2*

Let $b$ be a vectors with 1 rows and 2 column

\begin{equation}
a = \left[\begin{array}{c} b_{1} \\ b_{2}
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the vector dimension or shape is $(1,2)$ or $(1 \times 2)$


*Example 3*

A matrix has more than 1 row and more than 1 column.

Of course if the number of rows and columns are equal, it is called a *squared matrix*

In general , let $M$ be a matrix of dimension $(n,m)$ or $(n \times m)$

For the case of $n=3$ and $m=3$:

\begin{equation}
a = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1.3} \\
m_{2,1} & m_{2,2} & m_{2.3} \\
m_{3,1} & m_{3,2} & m_{3.3} \\
    \end{array}\right]
\end{equation}



In [24]:
# Example - column vector 

a = np.array([[4], [5], [6]])
print(a) 
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [14]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [19]:
# Example - Matrix 
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


# A nice track

In [21]:
# nr: store the number of rows
# nr: stores the number of columns
nr, nc = M.shape

# Size of DS

In python, size means the number of elements in a DS

In [22]:
M.size

9

In [23]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))

<class 'int'> <class 'numpy.ndarray'>


## 2.3 slicing

It is the same as string variable, only with minor modifications.

Let's see:

In [31]:
# Extract the 1st element

## column Vector
print(a[0,0])
print(type(a[0,0]))

## Row Vector
print(b[0,0])
print(type(a[0,0]))

## Matrix
print(M[1,1])

4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [32]:
# Extrac the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix 9


In [36]:
# Extract  subset

## Column Vector
print(a[0:2,0])

## Column Vector
print(a[0:2])

## Row Vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[4 5]
[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]
